source 'https://github.com/CocoaPods/Specs.git'





def import_pods
  pod "ABMSoundCloudAPI", :path => "../"

  pod "NSURLSession-Resplendent", :git => 'https://github.com/Resplendent/NSURLSession-Resplendent.git', :tag => 'v0.1.3'
end





target 'ABMSoundCloudAPI', :exclusive => true do
  import_pods
end

target 'Tests', :exclusive => true do
  import_pods
end
