source 'https://github.com/CocoaPods/Specs.git'





def import_pods
  pod "ABMSoundCloudAPI", :path => "../"
end





target 'ABMSoundCloudAPI', :exclusive => true do
  import_pods
end

target 'Tests', :exclusive => true do
  import_pods
end
