source 'https://github.com/CocoaPods/Specs.git'

def import_pods
  pod "ABMSoundCloudAPI", :path => "../"
end

target 'ABMSoundCloudAPI', :exclusive => true do
  import_pods
  pod "AFNetworking", "~> 2.5.0"
  pod "AFOAuth2Manager", "~> 2.2.0"
end

target 'Tests', :exclusive => true do
  import_pods
end
